"""Russian translations for the shared setup UI; Miro setting names stay recognizable."""

RU = {
    "Miro → Obsidian · Setup": "Miro → Obsidian · Настройка",
    "Your ideas, at home in your vault.": "Ваши идеи — в вашем хранилище.",
    "Getting started": "Начало работы",
    "01 \u00a0 Connect Miro": "01 \u00a0 Подключение Miro",
    "02 \u00a0 Choose a board": "02 \u00a0 Выбор доски",
    "03 \u00a0 Export to Canvas": "03 \u00a0 Экспорт в Canvas",
    "Runs on your computer": "Работает на вашем компьютере",
    "☾ Obsidian dark theme": "☾ Тёмная тема Obsidian",
    "A bridge to your knowledge": "Мост к вашим знаниям",
    "Bring your boards home.": "Ваши доски — в Obsidian.",
    "Connect Miro to start your journey to Obsidian Canvas.": "Подключите Miro, чтобы перенести доски в Obsidian Canvas.",
    "No Miro app yet?": "Ещё нет приложения Miro?",
    "Start here before entering Client ID or Client secret.": "Начните здесь, прежде чем вводить Client ID и Client secret.",
    "Open Miro Settings → Your apps": "Открыть Miro: Settings → Your apps",
    "Sign in in this browser. Miro may redirect to a company-specific settings address. If the link does not open Your apps, use your Miro avatar → Settings → Your apps.": "Войдите в этом браузере. Miro может перенаправить на страницу настроек вашей компании. Если Your apps не открывается по ссылке, нажмите на аватар в Miro → Settings → Your apps.",
    "In Your apps click ": "В разделе Your apps нажмите ",
    ", name it ": ", назовите приложение ",
    " and select a Developer team. Create a Developer team if Miro asks. The Explore the Developer Hub / Get started banner is optional; use Create new app below it.": " и выберите Developer team. Если Miro предложит, создайте команду разработчика. Баннер Explore the Developer Hub / Get started можно пропустить: нужная кнопка Create new app находится под ним.",
    "Set App URL / SDK URI to ": "Укажите App URL / SDK URI: ",
    " and OAuth redirect URI to ": " и OAuth redirect URI: ",
    ". Select Use this URI for SDK authorization if offered. Choose only ": ". Если доступно, включите Use this URI for SDK authorization. Выберите только права ",
    " and ": " и ",
    ", then save. Leave Expire user authorization token unchecked for unattended Code mode; this version does not renew expiring tokens.": ", затем сохраните. Для автоматизации оставьте Expire user authorization token выключенным: эта версия не обновляет токены с ограниченным сроком действия.",
    ", then save. Expiring authorization tokens are supported; the saved connection can renew them.": ", затем сохраните. Токены с ограниченным сроком действия поддерживаются: сохранённое подключение умеет их обновлять.",
    "Install and authorize the app in the team that owns your board. If installation is restricted, ask its administrator.": "Установите приложение и разрешите ему доступ в команде, которой принадлежит доска. Если установка ограничена, обратитесь к администратору команды.",
    "Keep this page and Miro in the same browser. If an email sign-in link opens another browser, finish setup in that browser too: login sessions do not transfer between browsers.": "Открывайте эту страницу и Miro в одном браузере. Если ссылка из письма открылась в другом браузере, завершите настройку там: сеансы входа между браузерами не переносятся.",
    "I have configured my Miro app — connect": "Приложение Miro настроено — подключить",
    "Copy the Client ID and Client secret from your own Miro app. They stay in this local process memory until OAuth finishes. Only the access token is saved in your operating system credential store.": "Скопируйте Client ID и Client secret из вашего приложения Miro. До завершения OAuth они находятся в памяти локального процесса. В хранилище учётных данных операционной системы сохраняется только токен доступа.",
    "Copy the Client ID and Client secret from your own Miro app. After you authorize in Miro, the connection (access and refresh tokens plus your Client ID and Client secret, so tokens can renew without you) is saved only in your operating system credential store, never in a file.": "Скопируйте Client ID и Client secret из вашего приложения Miro. После авторизации подключение (токены доступа и обновления, Client ID и Client secret для автоматического обновления) сохраняется только в хранилище учётных данных операционной системы, а не в файле.",
    "Client ID": "Client ID — идентификатор приложения",
    "Client secret": "Client secret — секрет приложения",
    "Connect to Miro": "Подключить Miro",
    "Miro setup": "Настройка Miro",
    "Ready to connect.": "Всё готово к подключению.",
    "Waiting for Miro authorization. Finish it in this browser, then refresh this page.": "Ожидаем разрешения в Miro. Завершите авторизацию в этом браузере, затем обновите страницу.",
    "Miro is connected. The access token is in your operating system credential store.": "Miro подключён. Токен доступа находится в хранилище учётных данных операционной системы.",
    "Miro is connected. The connection is saved in your operating system credential store.": "Miro подключён. Подключение сохранено в хранилище учётных данных операционной системы.",
    "Connection failed. Check the app credentials, redirect URI, and Miro permissions.": "Не удалось подключиться. Проверьте ключи приложения, redirect URI и права в Miro.",
    "Unknown setup state": "Неизвестное состояние настройки",
    "Continue to Miro authorization": "Перейти к авторизации в Miro",
    "Refresh status": "Обновить статус",
    "Miro → Obsidian · Local setup": "Miro → Obsidian · Локальная настройка",
}
