"""Generate the Web SDK presentation assets from the application's shared theme."""

from pathlib import Path

from miro2obsidian.ui_theme import THEME_SCRIPT, theme_css

SDK_CSS = """
.sdk-shell{max-width:1060px}.sdk-shell .rail{position:static}
.sdk-card{background:var(--surface);border:1px solid var(--border);border-radius:18px;padding:24px}
.controls{display:flex;flex-wrap:wrap;gap:10px}button:disabled{opacity:.5;cursor:default}
.controls button:not(#export-board),#create-generated-probe{background:var(--control);color:var(--ink);border:1px solid var(--border)}
.controls button:not(#export-board):hover,#create-generated-probe:hover{background:var(--control-hover)}
#export-board,#open-panel{background:var(--yellow);color:#242137}#export-board:hover,#open-panel:hover{background:#f4cf3e}
pre{overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;min-height:160px;max-height:55vh;padding:18px;
background:var(--canvas);border:1px solid var(--border);border-radius:12px;font:12px/1.65 Consolas,monospace}
.sdk-shell details{padding:18px;margin-top:18px}.sdk-version{color:var(--muted);font-size:12px}
@media(max-width:800px){.sdk-shell .rail{padding:16px 20px}.sdk-shell .theme-toggle{display:inline-block;margin:14px 10px 0 0}
.sdk-shell .language-switch{display:inline-flex}.sdk-shell h1{font-size:27px}.sdk-card{padding:18px}}
"""


def build(directory: Path | None = None) -> None:
    destination = directory or Path(__file__).resolve().parents[1] / "tools" / "miro_websdk_exporter"
    destination.mkdir(parents=True, exist_ok=True)
    (destination / "theme.css").write_text("/* Generated by scripts.build_ui_assets. */\n" + theme_css() + SDK_CSS, encoding="utf-8")
    (destination / "ui.js").write_text("// Generated by scripts.build_ui_assets.\n" + THEME_SCRIPT, encoding="utf-8")


if __name__ == "__main__":
    build()
