from __future__ import annotations

import argparse
import json
import os
from copy import deepcopy
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any


DEFAULT_BOARD_NAME = "Miro2Obsidian REST Capability Probe"
DEFAULT_BASE_URL = "https://api.miro.com/v2"


class MiroRestRequestError(RuntimeError):
    def __init__(self, message: str, *, status_code: int | str, response_body: str) -> None:
        super().__init__(message)
        self.status_code = status_code
        self.response_body = response_body


@dataclass(frozen=True)
class ProbeOperation:
    key: str
    item_type: str
    method: str
    path: str
    payload: dict[str, Any]
    depends_on: tuple[str, ...] = ()


def _position(col: int, row: int) -> dict[str, int]:
    return {"x": -420 + col * 360, "y": -260 + row * 220}


def build_probe_operations() -> list[ProbeOperation]:
    return [
        ProbeOperation(
            key="frame_main",
            item_type="frame",
            method="POST",
            path="/boards/{board_id}/frames",
            payload={
                "data": {"title": "REST probe frame"},
                "position": {"x": 0, "y": 0},
                "geometry": {"width": 1050, "height": 720},
            },
        ),
        ProbeOperation(
            key="text_html",
            item_type="text",
            method="POST",
            path="/boards/{board_id}/texts",
            payload={
                "data": {"content": "<p><strong>REST text probe</strong><br/>HTML content</p>"},
                "position": _position(0, 0),
                "geometry": {"width": 280},
            },
        ),
        ProbeOperation(
            key="shape_round_rect",
            item_type="shape",
            method="POST",
            path="/boards/{board_id}/shapes",
            payload={
                "data": {"content": "<p>REST shape probe</p>", "shape": "round_rectangle"},
                "position": _position(1, 0),
                "geometry": {"width": 260, "height": 120},
            },
        ),
        ProbeOperation(
            key="sticky_note",
            item_type="sticky_note",
            method="POST",
            path="/boards/{board_id}/sticky_notes",
            payload={
                "data": {"content": "REST sticky note probe"},
                "position": _position(2, 0),
                "geometry": {"width": 220},
            },
        ),
        ProbeOperation(
            key="card_basic",
            item_type="card",
            method="POST",
            path="/boards/{board_id}/cards",
            payload={
                "data": {
                    "title": "REST card probe",
                    "description": "Card description should survive export.",
                },
                "position": _position(0, 1),
            },
        ),
        ProbeOperation(
            key="app_card_fields",
            item_type="app_card",
            method="POST",
            path="/boards/{board_id}/app_cards",
            payload={
                "data": {
                    "title": "REST app card probe",
                    "description": "App card description should survive export.",
                    "fields": [
                        {"label": "Status", "value": "Probe"},
                        {"label": "Priority", "value": "High"},
                    ],
                },
                "position": _position(1, 1),
            },
        ),
        ProbeOperation(
            key="connector_shape_to_sticky",
            item_type="connector",
            method="POST",
            path="/boards/{board_id}/connectors",
            payload={
                "startItem": {"id": "$shape_round_rect.id"},
                "endItem": {"id": "$sticky_note.id"},
                "shape": "elbowed",
            },
            depends_on=("shape_round_rect", "sticky_note"),
        ),
    ]


def build_manifest(board_name: str = DEFAULT_BOARD_NAME) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "kind": "miro_rest_capability_probe",
        "board": {
            "name": board_name,
            "description": "Generated by scripts/miro_rest_probe_board.py for Miro -> Obsidian source coverage tests.",
        },
        "operations": [asdict(operation) for operation in build_probe_operations()],
    }


def resolve_placeholders(value: Any, results: dict[str, dict[str, Any]]) -> Any:
    if isinstance(value, str) and value.startswith("$"):
        parts = value[1:].split(".")
        if len(parts) != 2:
            return value
        result_key, field = parts
        if result_key not in results:
            raise KeyError(f"Missing dependency result for placeholder {value!r}")
        return results[result_key][field]
    if isinstance(value, list):
        return [resolve_placeholders(item, results) for item in value]
    if isinstance(value, dict):
        return {key: resolve_placeholders(item, results) for key, item in value.items()}
    return value


def planned_requests(manifest: dict[str, Any], board_id: str, base_url: str = DEFAULT_BASE_URL) -> list[dict[str, Any]]:
    requests: list[dict[str, Any]] = []
    for operation in manifest.get("operations", []):
        path = str(operation["path"]).format(board_id=board_id)
        requests.append(
            {
                "key": operation["key"],
                "item_type": operation["item_type"],
                "method": operation["method"],
                "url": base_url.rstrip("/") + path,
                "payload": deepcopy(operation["payload"]),
                "depends_on": list(operation.get("depends_on") or []),
            }
        )
    return requests


def _response_body(response: Any) -> str:
    try:
        return json.dumps(response.json(), ensure_ascii=False)
    except ValueError:
        return str(getattr(response, "text", ""))


def _post_json(session: Any, url: str, token: str, payload: dict[str, Any]) -> dict[str, Any]:
    response = session.post(
        url,
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        json=payload,
        timeout=30,
    )
    if not getattr(response, "ok", False):
        status_code = getattr(response, "status_code", "unknown")
        body = _response_body(response)
        raise MiroRestRequestError(
            f"Miro REST request failed with HTTP {status_code}: {body}",
            status_code=status_code,
            response_body=body,
        )
    return response.json()


def execute_manifest(
    manifest: dict[str, Any],
    token: str,
    *,
    board_id: str | None = None,
    base_url: str = DEFAULT_BASE_URL,
    session: Any | None = None,
) -> dict[str, Any]:
    if session is None:
        import requests

        session = requests.Session()

    results: dict[str, dict[str, Any]] = {}
    created_board = None
    if not board_id:
        created_board = _post_json(session, base_url.rstrip("/") + "/boards", token, manifest["board"])
        board_id = str(created_board["id"])

    for request in planned_requests(manifest, board_id, base_url=base_url):
        payload = resolve_placeholders(request["payload"], results)
        try:
            results[request["key"]] = _post_json(session, request["url"], token, payload)
        except MiroRestRequestError as exc:
            return {
                "ok": False,
                "board_id": board_id,
                "created_board": created_board,
                "items": results,
                "failed_request": {
                    "key": request["key"],
                    "item_type": request["item_type"],
                    "method": request["method"],
                    "url": request["url"],
                    "payload": payload,
                    "status_code": exc.status_code,
                    "response_body": exc.response_body,
                },
            }

    return {
        "ok": True,
        "board_id": board_id,
        "created_board": created_board,
        "items": results,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create or print a REST capability-probe Miro board manifest.")
    parser.add_argument("--board-name", default=DEFAULT_BOARD_NAME)
    parser.add_argument("--board-id", help="Existing board id. If omitted with --execute, the script creates a board.")
    parser.add_argument("--execute", action="store_true", help="Actually call the Miro REST API. Default is dry-run.")
    parser.add_argument("--token-env", default="MIRO_ACCESS_TOKEN", help="Environment variable containing a Miro token.")
    parser.add_argument("--oauth", action="store_true", help="Run local OAuth flow instead of reading --token-env.")
    parser.add_argument("--oauth-client-id-env", default="MIRO_CLIENT_ID")
    parser.add_argument("--oauth-client-secret-env", default="MIRO_CLIENT_SECRET")
    parser.add_argument("--oauth-redirect-uri", default="http://localhost:8000/callback")
    parser.add_argument("--oauth-scopes", default="boards:read boards:write team:read")
    parser.add_argument("--oauth-authorize-url", default="https://miro.com/app-install/")
    parser.add_argument("--oauth-token-url", default="https://api.miro.com/v1/oauth/token")
    parser.add_argument("--oauth-timeout-seconds", type=int, default=300)
    parser.add_argument("--oauth-no-open-browser", action="store_true")
    parser.add_argument("--oauth-code", help="Exchange an already obtained authorization code.")
    parser.add_argument("--oauth-callback-url", help="Exchange a copied localhost callback URL containing ?code=...")
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL)
    parser.add_argument("--output", type=Path, help="Write manifest/result JSON to this path.")
    return parser.parse_args()


def resolve_token_from_args(args: argparse.Namespace) -> str:
    if args.oauth:
        from miro_oauth_token import authorize_and_get_token, config_from_env, exchange_manual_authorization

        config = config_from_env(
            client_id_env=args.oauth_client_id_env,
            client_secret_env=args.oauth_client_secret_env,
            redirect_uri=args.oauth_redirect_uri,
            scopes=args.oauth_scopes,
            authorize_url=args.oauth_authorize_url,
            token_url=args.oauth_token_url,
        )
        if args.oauth_code or args.oauth_callback_url:
            return exchange_manual_authorization(
                config,
                code=args.oauth_code,
                callback_url=args.oauth_callback_url,
            )
        return authorize_and_get_token(
            config,
            timeout_seconds=args.oauth_timeout_seconds,
            open_browser=not args.oauth_no_open_browser,
        )

    token = os.environ.get(args.token_env)
    if not token:
        raise SystemExit(f"{args.token_env} is not set. Set it or pass --oauth.")
    return token


def main() -> int:
    args = parse_args()
    manifest = build_manifest(args.board_name)
    if args.execute:
        try:
            token = resolve_token_from_args(args)
        except (TimeoutError, RuntimeError) as exc:
            raise SystemExit(str(exc)) from exc
        output = execute_manifest(manifest, token, board_id=args.board_id, base_url=args.base_url)
    else:
        output = manifest

    text = json.dumps(output, ensure_ascii=False, indent=2)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text + "\n", encoding="utf-8")
    else:
        print(text)
    if isinstance(output, dict) and output.get("ok") is False:
        failed = output.get("failed_request") or {}
        print(f"failed_request={failed.get('key')} status={failed.get('status_code')}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
